[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "simple-apps-agent"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
  "mlflow>=3.1.0",
  "databricks-sdk",
  "databricks-openai",
  "databricks-langchain",
  "langchain",
  "langgraph",
]

[project.scripts]
start-app = "app:main"
